export const WAHAEvents = [
    "session.status",
    "message",
    "message.any",
    "message.reaction",
    "message.ack",
    "message.waiting",
    "message.revoked",
    "chat.archive",
    "group.v2.join",
    "group.v2.leave",
    "group.v2.update",
    "group.v2.participants",
    "group.join",
    "group.leave",
    "presence.update",
    "poll.vote",
    "poll.vote.failed",
    "call.received",
    "call.accepted",
    "call.rejected",
    "label.upsert",
    "label.deleted",
    "label.chat.added",
    "label.chat.deleted",
    "engine.event",
]
export const WAHAEventColor = {
    "session.status": "#64c4ff",
    "message": "#ffd429",
    "message.any": "#dfaef0",
    "message.reaction": "#99b6c1",
    "message.ack": "#55ccb3",
    "message.waiting": "#ff9dff",
    "message.revoked": "#d3a91d",
    "chat.archive": "#6d7cce",
    "group.v2.join": "#d7e752",
    "group.v2.leave": "#00d0e2",
    "group.v2.update": "#ffc5c7",
    "group.v2.participants": "#93ceac",
    "group.join": "#d7e752",
    "group.leave": "#00d0e2",
    "presence.update": "#ffc5c7",
    "poll.vote": "#93ceac",
    "poll.vote.failed": "#f74848",
    "call.received": "#00a0f2",
    "call.accepted": "#83e422",
    "call.rejected": "#ffaf04",
    "label.upsert": "#b5ebff",
    "label.deleted": "#9ba6ff",
    "label.chat.added": "#9368cf",
    "label.chat.deleted": "#64c4ff",
    "engine.event": "#ff9dff",
}
